// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Bet struct {
	UserID    sql.NullInt64
	GameID    sql.NullInt64
	Amount    sql.NullString
	UserLost  sql.NullBool
	CreatedAt sql.NullTime
}

type Game struct {
	ID          int32
	Title       sql.NullString
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Promotion struct {
	ID        int64
	Bonus     string
	Quantity  int32
	CreatedAt sql.NullTime
}

type PromotionsClaimed struct {
	IDUser      sql.NullInt64
	IDPromotion sql.NullInt64
	CreatedAt   sql.NullTime
}

type Transaction struct {
	ID              int64
	UserID          sql.NullInt64
	TransactionType string
	Amount          string
	TransactionDate sql.NullTime
}

type User struct {
	ID         int64
	Username   string
	Email      string
	Phone      sql.NullString
	Password   string
	Affiliated sql.NullBool
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type UserAffiliate struct {
	SponsorID   sql.NullInt64
	AssociateID sql.NullInt64
	CreatedAt   sql.NullTime
}

type UserBalance struct {
	UserID    sql.NullInt64
	Balance   sql.NullString
	TotalBets sql.NullString
	UpdatedAt sql.NullTime
}

type UserInfo struct {
	UserID    sql.NullInt64
	Birthdate sql.NullTime
	Cpf       sql.NullString
	Country   sql.NullString
	Uf        sql.NullString
	Cep       sql.NullString
	Address   sql.NullString
	UpdatedAt sql.NullTime
}
